services:    
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'caddy'
    restart: unless-stopped
    networks:
      - caddy_net
      - cloudflare
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - .env

  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    env_file:
      - .env
    depends_on:
      - caddy
    networks:
      - cloudflare

volumes:
  caddy_data:
  caddy_config:

networks:
  caddy_net:
    name: caddy_net
    attachable: true
    external: true
  cloudflare:
    name: cloudflare
    attachable: true
